spring:
    application:
        name: snapp-pay-wallet-${user.name}

database:
    show-sql: false
    host: localhost
    port: 5432
    name: snapp_pay
    user: postgres
    password: postgres
    schema: public
    jdbc-url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    datasource-class: org.postgresql.ds.PGSimpleDataSource
    driver-class: org.postgresql.Driver
    dialect-class: org.hibernate.dialect.PostgresPlusDialect
    connection:
        maximum-pool-size: 30
        max-lifetime: 30000


server:
    port: 8080
logging:
    level:
        root: info

