spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${database.jdbc-url}
        driver-class-name: ${database.driver-class}
        username: ${database.user}
        password: ${database.password}
        hikari:
            maximum-pool-size: ${database.connection.maximum-pool-size}
    jpa:
        open-in-view: false
        show-sql: ${database.show-sql}
        hibernate:
            ddl-auto: update
        properties:
            #            hibernate.jdbc.time_zone: UTC
            jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            # modify batch size as necessary
            hibernate.query.fail_on_pagination_over_collection_fetch: true
            hibernate.query.in_clause_parameter_padding: true
            hibernate.default_schema: ${database.schema}
            hibernate.dialect: ${database.dialect-class}
            hibernate.show_sql: ${database.show-sql}
            hibernate.format_sql: false
            hibernate.order_by.default_null_ordering: last
            hibernate.envers.audit_table_suffix: _histories

    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    profiles:
        active: develop
    jackson:
        default-property-inclusion: non_empty
    main:
        allow-bean-definition-overriding: true
    pid:
        fail-on-write-error: true
        file: ${user.home}/logs/snapp-pay/application/${spring.application.name}/${spring.application.name}.pid


server:
    servlet:
        context-path: /api

management:
    server:
        base-path: /api

logging:
    level:
        root: info
    file:
        name: ${user.home}/logs/application/${spring.application.name}/${spring.application.name}.log
